name: tvtudo
description: "A Brazilian TV streaming app"
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_platform_interface: ^2.10.0
  svg_image: ^0.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
